
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_service_arm
    username: root
    password: Nattarat999
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true

server:
  port: 7000